Repository codesquad-members-2025/be-was-neon, pull requests merged in 2025-04, with the labels that each got.

#1 [빙빙] step7-1 index.html 응답
  .idea/compiler.xml
  .idea/misc.xml
  README.md
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestParser.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/loader/ClasspathResourceLoader.java
  src/main/java/webserver/loader/FileResourceLoader.java
  src/main/java/webserver/loader/ResourceLoader.java
  src/test/java/webserver/RequestParserTest.java
Labels: Step7-1

#2 [디노] step7-1 웹 서버 1단계 - index.html 응답
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/vcs.xml
  README.md
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/utils/HttpRequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/test/java/utils/HttpRequestParserTest.java
Labels: Step7-1

#3 [Glad] Step 7-1, 7-2 index.html & 다양한 컨텐츠 지원
  .idea/compiler.xml
  .idea/misc.xml
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/http/exception/RequestParseException.java
  src/main/java/webserver/resolver/ResourceResolver.java
  src/test/java/webserver/http/HttpRequestTest.java
  src/test/java/webserver/http/HttpResponseTest.java
  src/test/java/webserver/resolver/ResourceResolverTest.java
Labels: Step7-1, Step7-2

#4 [Elbin] step - 1 웹 서버 1단계 - index.html 응답
  .idea/compiler.xml
  .idea/misc.xml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1

#5 [빙빙] step 7-2 다양한 컨텐츠 타입 지원
  README.md
  src/main/java/webserver/ContentTypeResolver.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestParser.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/loader/ClasspathResourceLoader.java
  src/main/java/webserver/request/RequestHandler.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/response/ResponseHandler.java
  src/test/java/webserver/RequestParserTest.java
Labels: Step7-2

#6 [케이딘] step7-1 index.html 응답
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  README.md
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1

#7 Feature1
  .idea/compiler.xml
  .idea/misc.xml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestHandlerV2.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1, Step7-2

#8 [BRIE] Step 7-2 웹 서버 1단계 - index.html 응답
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/util/ContentTypeMapper.java
  src/main/java/webserver/util/RequestParser.java
Labels: Step7-1

#9 [디노] step7-2 웹 서버 2단계 - 다양한 컨텐츠 타입 지원
  README.md
  src/main/java/loader/ResourceData.java
  src/main/java/loader/StaticResourceLoader.java
  src/main/java/request/RequestHeader.java
  src/main/java/request/RequestHeaderReader.java
  src/main/java/response/ContentTypeMapper.java
  src/main/java/response/ResponseBuilder.java
  src/main/java/utils/FileExtentionExtractor.java
  src/main/java/utils/HttpRequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/test/java/utils/HttpRequestParserTest.java
Labels: Step7-2

#10 [지토] step7-1 웹 서버 1단계 - index.html 응답
  README.md
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1

#11 [MUD] Step 7 - index.html 응답
  .gitignore
  .idea/compiler.xml
  .idea/misc.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1

#12 [훈] Step7-1 - index.html 응답
  .gitignore
  .idea/misc.xml
  src/main/java/utils/HttpRequestUtils.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1

#13 [케이딘] step 7-2 다양한 컨텐츠 타입 지원
  .gitignore
  src/main/java/http/ContentType.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/RequestParser.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/loader/FileResourceLoader.java
  src/main/java/webserver/loader/ResourceLoader.java
Labels: Step7-2

#14 [빙빙] step 7-3 GET으로 회원가입
  README.md
  src/main/java/webserver/ContentTypeResolver.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/common/Constants.java
  src/main/java/webserver/common/HttpStatus.java
  src/main/java/webserver/loader/ClasspathResourceLoader.java
  src/main/java/webserver/loader/FileResourceLoader.java
  src/main/java/webserver/loader/ResourceLoader.java
  src/main/java/webserver/request/RequestHandler.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/response/Response.java
  src/main/java/webserver/response/ResponseHandler.java
  src/main/java/webserver/response/ResponseHeader.java
  src/main/java/webserver/response/ResponseHeaderFactory.java
  src/main/resources/static/registration/index.html
  src/test/java/webserver/RequestParserTest.java
Labels: Step7-3

#15 [디노] step7-3 웹 서버 3단계 - GET으로 회원가입
  README.md
  src/main/java/loader/StaticResourceLoader.java
  src/main/java/model/User.java
  src/main/java/response/ContentTypeMapper.java
  src/main/java/response/ResponseBuilder.java
  src/main/java/response/handler/CreateUserHandler.java
  src/main/java/response/handler/Handler.java
  src/main/java/response/handler/StaticResourceHandler.java
  src/main/java/utils/QueryStringParser.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
Labels: Step7-3

#16 [Glad] Step 7-3 웹 서버 3단계 - GET으로 회원가입
  .gitignore
  README.md
  build.gradle
  src/main/java/db/Database.java
  src/main/java/handler/Handler.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/annotation/RequestMapping.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/http/common/ContentType.java
  src/main/java/webserver/http/common/HttpConstants.java
  src/main/java/webserver/http/common/HttpHeaders.java
  src/main/java/webserver/http/common/HttpMethod.java
  src/main/java/webserver/http/exception/HeaderNotFoundException.java
  src/main/java/webserver/http/exception/HttpException.java
  src/main/java/webserver/http/request/ABNFRequestParser.java
  src/main/java/webserver/http/request/HttpRequest.java
  src/main/java/webserver/http/request/RequestLine.java
  src/main/java/webserver/http/response/HttpResponse.java
  src/main/java/webserver/http/response/HttpStatusCode.java
  src/main/java/webserver/http/response/StatusLine.java
  src/main/java/webserver/mapper/HandlerMapper.java
  src/main/java/webserver/resolver/DynamicHandler.java
  src/main/java/webserver/resolver/DynamicResolver.java
  src/main/java/webserver/resolver/ResolveResponse.java
  src/main/java/webserver/resolver/Resolver.java
  src/main/java/webserver/resolver/ResourceResolver.java
  src/main/java/webserver/util/Convertor.java
  src/main/java/webserver/util/Serializer.java
  src/main/resources/static/registration/index.html
  src/test/java/webserver/http/HttpRequestTest.java
  src/test/java/webserver/http/HttpResponseTest.java
  src/test/java/webserver/http/request/ABNFRequestParserTest.java
  src/test/java/webserver/http/request/HttpRequestTest.java
  src/test/java/webserver/http/request/RequestLineTest.java
  src/test/java/webserver/http/response/HttpResponseTest.java
  src/test/java/webserver/resolver/ResourceResolverTest.java
  src/test/java/webserver/util/ConvertorTest.java
  src/test/java/webserver/util/SerializerTest.java
Labels: Step7-3

#18 [BRIE] Step7-2 다양한 컨텐츠 타입 지원
  README.md
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/util/ContentType.java
  src/main/java/webserver/util/ContentTypeMapper.java
  src/main/java/webserver/util/RequestParser.java
Labels: Step7-2

#19 [Elbin] step-2 웹 서버 2단계 - 다양한 컨텐츠 타입 지원
  src/main/java/webserver/ContentTypeMapper.java
  src/main/java/webserver/RequestHandler.java
Labels: Step7-2

#17 [지토] step7-2 웹 서버 2단계 - 다양한 컨텐츠 타입 지원
  src/main/java/webserver/ContentType.java
  src/main/java/webserver/RequestHandler.java
Labels: Step7-2

#20 [JOHNNIE] 웹 서버 4단계 - POST로 회원 가입
  src/main/java/controller/UserController.java
  src/main/java/converter/ToJsonConverter.java
  src/main/java/domain/ContentType.java
  src/main/java/domain/error/HttpClientError.java
  src/main/java/domain/error/HttpServerError.java
  src/main/java/exception/ClientException.java
  src/main/java/exception/HttpException.java
  src/main/java/exception/ServerException.java
  src/main/java/handler/HttpResponseHelper.java
  src/main/java/handler/RequestHandlerV2.java
  src/main/java/handler/StaticRequestHandler.java
  src/main/java/handler/UserRequestHandler.java
  src/main/java/webserver/RequestHandlerV2.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/registration/index.html
Labels: Step8-1

#22 [Glad] Step 8-1 웹 서버 4단계 - POST로 회원 가입
  README.md
  src/main/java/handler/Handler.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/http/common/HttpHeaders.java
  src/main/java/webserver/http/request/RequestLine.java
  src/main/java/webserver/http/request/RequestParser.java
  src/main/java/webserver/http/response/HttpStatusCode.java
  src/main/java/webserver/resolver/ResolveResponse.java
  src/main/java/webserver/util/Convertor.java
  src/main/java/webserver/util/QueryStringParser.java
  src/main/resources/static/registration/index.html
  src/test/java/webserver/http/request/RequestLineTest.java
  src/test/java/webserver/http/request/RequestParserTest.java
  src/test/java/webserver/util/QueryStringParserTest.java
Labels: Step8-1

#23 [MUD] Step7-2 다양한 컨텐츠 타입 지원
  src/main/java/http/Request.java
  src/main/java/util/ContentType.java
  src/main/java/util/FileContentUtil.java
  src/main/java/webserver/DispatcherHandler.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/ResponseHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/error/404.html
Labels: Step7-2

#25 [빙빙] step 8-1 POST로 회원 가입
  README.md
  build.gradle
  src/main/java/handler/CreateUserHandler.java
  src/main/java/handler/Handler.java
  src/main/java/handler/StaticFileHandler.java
  src/main/java/handler/errorHandler/InternalServerErrorHandler.java
  src/main/java/handler/errorHandler/MethodNotAllowedHandler.java
  src/main/java/handler/errorHandler/NotFoundHandler.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/common/Constants.java
  src/main/java/webserver/common/HttpMethod.java
  src/main/java/webserver/common/HttpStatus.java
  src/main/java/webserver/exception/HttpException.java
  src/main/java/webserver/exception/MethodNotAllowedException.java
  src/main/java/webserver/exception/ResourceNotFoundException.java
  src/main/java/webserver/exception/ServerErrorException.java
  src/main/java/webserver/loader/ClasspathResourceLoader.java
  src/main/java/webserver/loader/FileResourceLoader.java
  src/main/java/webserver/loader/ResourceLoader.java
  src/main/java/webserver/request/Request.java
  src/main/java/webserver/request/RequestHandler.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/resolver/ContentTypeResolver.java
  src/main/java/webserver/resolver/ErrorResolver.java
  src/main/java/webserver/resolver/MethodResolver.java
  src/main/java/webserver/response/ResponseHandler.java
  src/main/resources/static/error/404.html
  src/main/resources/static/error/405.html
  src/main/resources/static/error/500.html
  src/main/resources/static/registration/index.html
  src/test/java/handler/CreateUserHandlerTest.java
  src/test/java/handler/errorHandler/InternalServerErrorHandlerTest.java
  src/test/java/handler/errorHandler/MethodNotAllowedHandlerTest.java
  src/test/java/handler/errorHandler/NotFoundHandlerTest.java
  src/test/java/webserver/RequestParserTest.java
  src/test/java/webserver/resolver/ContentTypeResolverTest.java
Labels: Step8-1

#27 [훈] Step7-2 다양한 컨텐츠 타입 지원
  src/main/java/utils/ContentType.java
  src/main/java/utils/HttpRequestUtils.java
  src/main/java/utils/HttpStatus.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/request/HttpRequest.java
  src/main/java/webserver/request/HttpRequestParser.java
  src/main/java/webserver/response/HttpResponse.java
  src/main/resources/static/img/cloud.png
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
Labels: Step7-2

#29 [BRIE] Step7-3 get으로 회원가입
  README.md
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/handler/Handler.java
  src/main/java/webserver/handler/NotFoundHandler.java
  src/main/java/webserver/handler/StaticFileHandler.java
  src/main/java/webserver/handler/UserCreateHandler.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/util/ContentType.java
  src/main/java/webserver/util/RequestParser.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
Labels: Step7-3

#30 [Elbin] step-3 웹 서버 3단계 - GET으로 회원가입
  src/main/java/handler/StaticFileHandler.java
  src/main/java/handler/UserRequestHandler.java
  src/main/java/request/RequestRouter.java
  src/main/java/response/HttpResponseWriter.java
  src/main/java/utils/RequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
Labels: Step7-3

#31 [JOHNNIE] -웹 서버 5단계 - 쿠키를 이용한 로그인
  src/main/java/controller/UserController.java
  src/main/java/db/Database.java
  src/main/java/dto/HttpRequest.java
  src/main/java/dto/HttpResponse.java
  src/main/java/dto/LoginRequest.java
  src/main/java/dto/UserCreateRequest.java
  src/main/java/frontHandler/FrontHandlerContainer.java
  src/main/java/frontHandler/HandlerAdapter.java
  src/main/java/frontHandler/ModelView.java
  src/main/java/frontHandler/adapter/ReturnViewPathAdapter.java
  src/main/java/handler/HttpResponseHelper.java
  src/main/java/handler/LoginHandler.java
  src/main/java/handler/RequestHandlerV2.java
  src/main/java/handler/ReturnViewPathHandler.java
  src/main/java/handler/StaticRequestHandler.java
  src/main/java/handler/UserRequestHandler.java
  src/main/java/response/HttpResponseRender.java
  src/main/java/service/LoginService.java
  src/main/java/service/UserService.java
  src/main/java/session/SessionManager.java
  src/main/java/utils/AuthUtils.java
  src/main/java/utils/parser/HttpRequestParser.java
  src/main/java/utils/parser/HttpResponseParser.java
  src/main/java/utils/parser/ToJsonParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/login/index.html
  src/main/resources/static/user/login_failed.html
Labels: Step8-2

#32 [배찌] step1 - index.html 응답
  .idea/compiler.xml
  .idea/misc.xml
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/WebServer.java
  src/main/java/util/MyLogger.java
  src/main/java/webserver/HttpRequest.java
  src/main/java/webserver/HttpRequestHandler.java
  src/main/java/webserver/HttpResponse.java
  src/main/java/webserver/HttpServer.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
Labels: Step7-1

#33 [빙빙] step8-2 쿠키를 이용한 로그인
  README.md
  src/main/java/db/Database.java
  src/main/java/handler/CreateUserHandler.java
  src/main/java/handler/Handler.java
  src/main/java/handler/LoginHandler.java
  src/main/java/handler/LogoutHandler.java
  src/main/java/handler/errorHandler/UnauthorizedHandler.java
  src/main/java/webserver/common/Constants.java
  src/main/java/webserver/common/HttpMethod.java
  src/main/java/webserver/common/HttpStatus.java
  src/main/java/webserver/exception/NotRegisteredUserException.java
  src/main/java/webserver/request/Request.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/resolver/ErrorResolver.java
  src/main/java/webserver/resolver/MethodResolver.java
  src/main/java/webserver/response/Response.java
  src/main/java/webserver/response/ResponseHeader.java
  src/main/java/webserver/response/ResponseHeaderFactory.java
  src/main/java/webserver/session/Session.java
  src/main/java/webserver/session/SessionManager.java
  src/main/resources/static/login/fail.html
  src/main/resources/static/login/index.html
  src/test/java/handler/LoginHandlerTest.java
  src/test/java/handler/LogoutHandlerTest.java
  src/test/java/webserver/RequestParserTest.java
Labels: Step8-2

#35 [MUD] Step7-3 GET으로 회원가입
  src/main/java/util/FileContentUtil.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/DispatcherHandler.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/ResponseHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/http/common/ContentType.java
  src/main/java/webserver/http/common/StatusCode.java
  src/main/java/webserver/http/common/UrlPattern.java
  src/main/java/webserver/http/request/Request.java
  src/main/java/webserver/http/request/RequestParser.java
  src/main/java/webserver/http/response/Response.java
  src/main/java/webserver/http/response/ResponseWriter.java
  src/main/java/webserver/http/response/handler/DynamicHandler.java
  src/main/java/webserver/http/response/handler/Handler.java
  src/main/java/webserver/http/response/handler/StaticHandler.java
  src/main/resources/static/registration/index.html
Labels: Step7-3

#34 [Glad] Step 8-2 웹 서버 5단계 - 쿠키를 이용한 로그인
  README.md
  src/main/java/handler/Handler.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/http/common/CookieShop.java
  src/main/java/webserver/http/common/HttpHeaders.java
  src/main/java/webserver/http/common/HttpSession.java
  src/main/java/webserver/http/exception/HeaderNotFoundException.java
  src/main/java/webserver/http/request/HttpRequest.java
  src/main/java/webserver/mapper/HandlerMapper.java
  src/main/java/webserver/resolver/SessionResolver.java
  src/main/java/webserver/session/SessionManager.java
  src/main/java/webserver/util/QueryStringParser.java
  src/main/resources/static/login/index.html
  src/main/resources/static/login/login_failed.html
  src/test/java/handler/HandlerTest.java
  src/test/java/provider/RequestBuilder.java
  src/test/java/webserver/DispatcherTest.java
  src/test/java/webserver/http/common/CookieShopTest.java
  src/test/java/webserver/resolver/ResourceResolverTest.java
  src/test/java/webserver/resolver/SessionResolverTest.java
Labels: Step8-2

#36 [지토] step7-3 웹 서버 3단계 - GET으로 회원가입
  .idea/modules.xml
  .idea/modules/be-was-neon.iml
  .idea/modules/be-was-neon.test.iml
  src/main/java/controller/UserController.java
  src/main/java/dispatcher/RequestDispatcher.java
  src/main/java/handler/StaticFileHandler.java
  src/main/java/util/Parser.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/request/HttpRequest.java
  src/main/java/webserver/response/HttpResponse.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
  src/test/java/util/ParserTest.java
Labels: Step7-3

#37 [HOON] Step7-3 GET으로 회원가입
  src/main/java/router/DispatcherServlet.java
  src/main/java/router/RequestHandlerFunctional.java
  src/main/java/router/RequestRoute.java
  src/main/java/util/FileUtils.java
  src/main/java/webserver/common/ContentType.java
  src/main/java/webserver/common/HttpStatus.java
  src/main/java/webserver/http/request/HttpRequest.java
  src/main/java/webserver/http/request/HttpRequestParser.java
  src/main/java/webserver/http/response/HttpResponse.java
  src/main/java/webserver/server/RequestHandler.java
  src/main/java/webserver/server/WebServer.java
  src/main/resources/static/errors/403.html
  src/main/resources/static/errors/404.html
  src/main/resources/static/errors/500.html
  src/main/resources/static/registration/index.html
Labels: Step7-3

#38 [BRIE] Step8-1 post로 회원 가입
  README.md
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/handler/UserCreateHandler.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/util/FormBodyParser.java
  src/main/java/webserver/util/RequestParser.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
Labels: Step8-1

#39 [배찌] - step2 다양한 컨텐츠 타입 지원
  .idea/modules.xml
  .idea/modules/be-was-neon.test.iml
  src/main/java/WebServer.java
  src/main/java/model/User.java
  src/main/java/model/UserRepository.java
  src/main/java/webserver/HttpServer.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpRequestHandler.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/servlet/HttpServlet.java
  src/main/java/webserver/servlet/ServletManager.java
  src/main/java/webserver/servlet/StaticServlet.java
  src/main/java/webserver/servlet/UserCreateServlet.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
  src/test/java/webserver/http/HttpRequestTest.java
Labels: Step7-2, Step7-3, Step8-1

#40 [빙빙] step8-3 동적인 HTML
  README.md
  build.gradle
  src/main/java/handler/CreateUserHandler.java
  src/main/java/handler/Handler.java
  src/main/java/handler/LoginHandler.java
  src/main/java/handler/LogoutHandler.java
  src/main/java/handler/StaticFileHandler.java
  src/main/java/handler/TemplateHandler.java
  src/main/java/handler/errorHandler/InternalServerErrorHandler.java
  src/main/java/handler/errorHandler/MethodNotAllowedHandler.java
  src/main/java/handler/errorHandler/NotFoundHandler.java
  src/main/java/handler/errorHandler/UnauthorizedHandler.java
  src/main/java/template/HeaderRenderer.java
  src/main/java/template/TemplateRenderer.java
  src/main/java/template/UserListRenderer.java
  src/main/java/webserver/exception/UnauthorizedUserException.java
  src/main/java/webserver/loader/ClasspathResourceLoader.java
  src/main/java/webserver/loader/FileResourceLoader.java
  src/main/java/webserver/loader/ResourceLoader.java
  src/main/java/webserver/resolver/MethodResolver.java
  src/main/java/webserver/response/Response.java
  src/main/java/webserver/session/SessionManager.java
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list/index.html
  src/test/java/handler/LoginHandlerTest.java
  src/test/java/handler/TemplateHandlerTest.java
  src/test/java/handler/errorHandler/InternalServerErrorHandlerTest.java
  src/test/java/handler/errorHandler/MethodNotAllowedHandlerTest.java
  src/test/java/handler/errorHandler/NotFoundHandlerTest.java
  src/test/java/template/HeaderRendererTest.java
  src/test/java/template/UserListRendererTest.java
Labels: Step8-3

#41 [Elbin] step-4 웹 서버 4단계 - POST로 회원 가입
  src/main/java/handler/ErrorHandler.java
  src/main/java/handler/Handler.java
  src/main/java/handler/HandlerManager.java
  src/main/java/handler/StaticFileHandler.java
  src/main/java/handler/UserRequestHandler.java
  src/main/java/httpconst/HttpConst.java
  src/main/java/request/Request.java
  src/main/java/request/RequestHeader.java
  src/main/java/request/RequestReader.java
  src/main/java/request/RequestRouter.java
  src/main/java/request/RequestStatusLine.java
  src/main/java/response/HttpResponseWriter.java
  src/main/java/utils/RequestParser.java
  src/main/java/webserver/RequestHandler.java
  src/main/resources/static/registration/index.html
Labels: Step8-1

#43 [JOHNNIE] - 웹 서버 6단계 - 동적인 HTML
  src/main/java/dto/RouteKey.java
  src/main/java/frontHandler/FrontHandlerContainer.java
  src/main/java/frontHandler/adapter/ReturnViewPathAdapter.java
  src/main/java/handler/IndexHandler.java
  src/main/java/handler/LoginHandler.java
  src/main/java/handler/UserListHandler.java
  src/main/java/handler/UserRequestHandler.java
  src/main/java/handler/WriteHandler.java
  src/main/java/model/Article.java
  src/main/java/response/HttpResponseRender.java
  src/main/java/service/ArticleService.java
  src/main/java/service/LoginService.java
  src/main/java/service/UserService.java
  src/main/java/session/SessionManager.java
  src/main/java/utils/AuthUtils.java
  src/main/java/utils/DynamicHtmlBuilder.java
  src/main/java/utils/parser/HttpRequestParser.java
  src/main/java/utils/parser/HttpResponseParser.java
  src/main/java/utils/parser/ToJsonParser.java
  src/main/resources/static/index.html
  src/main/resources/static/user/list.html
  src/main/resources/static/write.html
Labels: Step8-3

#44 [지토] step8-1 웹 서버 4단계 - POST로 회원 가입
  src/main/java/controller/UserController.java
  src/main/java/dispatcher/RequestDispatcher.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/request/HttpRequest.java
  src/main/java/webserver/response/HttpResponse.java
  src/main/resources/static/registration/index.html
Labels: Step8-1

#45 [케이딘] step8-1 POST로 회원 가입
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/request/Dispatcher.java
  src/main/java/webserver/request/GetRequestHandler.java
  src/main/java/webserver/request/HttpRequest.java
  src/main/java/webserver/request/PostRequestHandler.java
  src/main/java/webserver/request/RequestHandler.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/response/HttpResponse.java
  src/main/java/webserver/response/ResponseHandler.java
  src/main/java/webserver/response/ResponseWriter.java
  src/main/java/webserver/util/ContentType.java
  src/main/resources/static/img/hawoon1.jpeg
  src/main/resources/static/img/hawoon2.jpeg
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
  src/test/java/webserver/request/RequestHandlerTest.java
  src/test/java/webserver/request/RequestParserTest.java
Labels: Step8-1

#46 [훈] step8-1 POST로 회원 가입
  src/main/java/router/DispatcherServlet.java
  src/main/java/router/RequestHandlerFunctional.java
  src/main/java/router/RequestRoute.java
  src/main/java/router/Router.java
  src/main/java/router/handler/HttpRequestHandler.java
  src/main/java/router/handler/impl/StaticFileHandler.java
  src/main/java/router/handler/impl/UserCreationHandler.java
  src/main/java/webserver/http/request/HttpRequest.java
  src/main/java/webserver/http/request/HttpRequestParser.java
  src/main/java/webserver/http/response/HttpResponse.java
  src/main/java/webserver/server/RequestHandler.java
  src/main/resources/static/errors/405.html
  src/main/resources/static/errors/409.html
  src/main/resources/static/registration/index.html
Labels: Step8-1

#48 [Glad] Step 8-3 웹 서버 6단계 - 동적인 HTML
  README.md
  src/main/java/handler/Handler.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/mapper/HandlerMapper.java
  src/main/java/webserver/model/Model.java
  src/main/java/webserver/resolver/ResolveResponse.java
  src/main/java/webserver/view/ModelAndView.java
  src/main/java/webserver/view/TemplateEngine.java
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user-list.html
  src/test/java/handler/HandlerTest.java
  src/test/java/webserver/DispatcherTest.java
  src/test/java/webserver/view/TemplateEngineTest.java
Labels: Step8-3

#50 [디노] step8-3 웹 서버 6단계 - 동적인 HTML
  README.md
  src/main/java/constants/HttpValues.java
  src/main/java/request/RequestHeader.java
  src/main/java/response/handler/DynamicHeaderHandler.java
  src/main/java/response/handler/LogoutHandler.java
  src/main/java/response/handler/StaticResourceHandler.java
  src/main/java/response/handler/UserListHandler.java
  src/main/java/session/SessionManager.java
  src/main/java/session/SessionUserResolver.java
  src/main/java/templates/HeaderModelBuilder.java
  src/main/java/templates/HtmlBuilder.java
  src/main/java/templates/ModelConstants.java
  src/main/java/templates/TemplateEngine.java
  src/main/java/webserver/Dispatcher.java
  src/main/resources/static/index.html
  src/main/resources/static/user/list.html
Labels: Step8-3

#51 [빙빙] step9-1 게시글 쓰기 구현
  README.md
  build.gradle
  src/main/java/db/ArticleDao.java
  src/main/java/db/Database.java
  src/main/java/db/JdbcUtils.java
  src/main/java/db/UserDao.java
  src/main/java/handler/Handler.java
  src/main/java/handler/article/ArticleDetailHandler.java
  src/main/java/handler/article/WriteArticleHandler.java
  src/main/java/handler/auth/CreateUserHandler.java
  src/main/java/handler/auth/LoginHandler.java
  src/main/java/handler/auth/LogoutHandler.java
  src/main/java/handler/util/PathResolvedHandler.java
  src/main/java/handler/view/MainPageHandler.java
  src/main/java/handler/view/TemplateHandler.java
  src/main/java/model/Article.java
  src/main/java/model/User.java
  src/main/java/template/ArticleContentRenderer.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/request/Request.java
  src/main/java/webserver/resolver/MethodResolver.java
  src/main/resources/static/main.css
  src/main/resources/templates/article/write.html
  src/main/resources/templates/index.html
  src/test/java/handler/CreateUserHandlerTest.java
  src/test/java/handler/LoginHandlerTest.java
  src/test/java/handler/LogoutHandlerTest.java
  src/test/java/handler/TemplateHandlerTest.java
  src/test/java/handler/WriteArticleHandlerTest.java
  src/test/java/handler/article/ArticleDetailHandlerTest.java
Labels: Step9-1

#52 [케이딘] step 8-2 쿠키를 이용한 로그인
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/handler/Dispatcher.java
  src/main/java/webserver/handler/GetRequestHandler.java
  src/main/java/webserver/handler/Handler.java
  src/main/java/webserver/handler/LoginHandler.java
  src/main/java/webserver/handler/LogoutHandler.java
  src/main/java/webserver/handler/NotFoundHandler.java
  src/main/java/webserver/handler/RegistrationHandler.java
  src/main/java/webserver/handler/RouteRegistry.java
  src/main/java/webserver/handler/RouteTable.java
  src/main/java/webserver/request/Dispatcher.java
  src/main/java/webserver/request/GetRequestHandler.java
  src/main/java/webserver/request/PostRequestHandler.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/response/HttpResponse.java
  src/main/java/webserver/response/ResponseHandler.java
  src/main/java/webserver/response/ResponseSender.java
  src/main/java/webserver/response/Status.java
  src/main/java/webserver/session/Session.java
  src/main/java/webserver/session/SessionMap.java
  src/main/java/webserver/util/Constants.java
  src/main/resources/static/login/index.html
  src/main/resources/static/login_failed/index.html
  src/test/java/webserver/request/RequestHandlerTest.java
Labels: Step8-2

#53 [훈] step 8-2 쿠키를 이용한 로그인
  src/main/java/router/DispatcherServlet.java
  src/main/java/router/RequestRoute.java
  src/main/java/router/RouteRegistry.java
  src/main/java/router/Router.java
  src/main/java/router/handler/impl/LoginHandler.java
  src/main/java/router/handler/impl/LogoutHandler.java
  src/main/java/router/handler/impl/MethodNotAllowHandler.java
  src/main/java/webserver/common/HttpMethod.java
  src/main/java/webserver/http/cookie/Cookie.java
  src/main/java/webserver/http/request/HttpRequest.java
  src/main/java/webserver/http/request/HttpRequestParser.java
  src/main/java/webserver/http/response/HttpResponse.java
  src/main/java/webserver/http/session/HttpSession.java
  src/main/java/webserver/http/session/SessionManager.java
  src/main/resources/static/index.html
  src/main/resources/static/login/fail/not-found-user.html
  src/main/resources/static/login/fail/not-required-parameters.html
  src/main/resources/static/login/fail/wrong-password.html
  src/main/resources/static/login/index.html
  src/main/resources/static/registration/index.html
Labels: Step8-2

#54 [MUD] Step8-2 쿠키를 이용한 로그인
  build.gradle
  src/main/java/exception/InvalidHttpMethodException.java
  src/main/java/exception/PasswordMismatchException.java
  src/main/java/exception/UserNotFoundException.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/http/common/StatusCode.java
  src/main/java/webserver/http/common/UrlPattern.java
  src/main/java/webserver/http/request/Request.java
  src/main/java/webserver/http/request/param/BodyParams.java
  src/main/java/webserver/http/request/param/CookieParams.java
  src/main/java/webserver/http/request/param/HeaderParams.java
  src/main/java/webserver/http/request/param/QueryParams.java
  src/main/java/webserver/http/request/param/RequestLineParams.java
  src/main/java/webserver/http/request/parser/CookieParser.java
  src/main/java/webserver/http/request/parser/QueryParser.java
  src/main/java/webserver/http/request/parser/RequestLineParser.java
  src/main/java/webserver/http/request/parser/RequestParser.java
  src/main/java/webserver/http/response/Response.java
  src/main/java/webserver/http/response/ResponseBuilder.java
  src/main/java/webserver/http/response/handler/DynamicHandler.java
  src/main/java/webserver/http/response/handler/StaticHandler.java
  src/main/java/webserver/http/session/Session.java
  src/main/java/webserver/http/session/SessionContainer.java
  src/main/resources/static/index.html
  src/main/resources/static/registration/index.html
  src/main/resources/static/user/login.html
  src/main/resources/static/user/login_failed.html
  src/test/java/webserver/http/response/handler/DynamicHandlerTest.java
Labels: Step8-2

#55 [BRIE] Step8-2 쿠키를 이용한 로그인
  README.md
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/RequestHandler.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/exception/BadRequestException.java
  src/main/java/webserver/exception/InternalServerErrorException.java
  src/main/java/webserver/exception/MethodNotAllowedException.java
  src/main/java/webserver/exception/NotFoundException.java
  src/main/java/webserver/handler/AuthHandler.java
  src/main/java/webserver/handler/ExceptionHandler.java
  src/main/java/webserver/handler/Handler.java
  src/main/java/webserver/handler/NotFoundHandler.java
  src/main/java/webserver/handler/StaticFileHandler.java
  src/main/java/webserver/handler/UserCreateHandler.java
  src/main/java/webserver/handler/UserLoginHandler.java
  src/main/java/webserver/handler/UserLogoutHandler.java
  src/main/java/webserver/http/HttpException.java
  src/main/java/webserver/http/HttpRequest.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/session/Session.java
  src/main/java/webserver/session/SessionCleaner.java
  src/main/java/webserver/session/SessionManager.java
  src/main/java/webserver/util/CookieParser.java
  src/main/java/webserver/util/RequestParser.java
  src/main/java/webserver/util/Route.java
  src/main/resources/static/img/IMG_0204.jpg
  src/main/resources/static/index.html
  src/main/resources/static/login/index.html
Labels: Step8-2

#57 [배찌] step8-3 - 동적인 HTML
  .idea/misc.xml
  .idea/modules.xml
  .idea/modules/be-was-neon.test.iml
  src/main/java/WebServer.java
  src/main/java/util/SessionUtil.java
  src/main/java/webserver/HttpServer.java
  src/main/java/webserver/handler/AuthController.java
  src/main/java/webserver/http/ContentType.java
  src/main/java/webserver/http/HttpResponse.java
  src/main/java/webserver/http/HttpSession.java
  src/main/java/webserver/http/Session.java
  src/main/java/webserver/http/SessionManager.java
  src/main/java/webserver/http/Status.java
  src/main/java/webserver/servlet/AnnotationServlet.java
  src/main/java/webserver/servlet/ServletManager.java
  src/main/java/webserver/servlet/StaticServlet.java
  src/main/java/webserver/template/Template.java
  src/main/resources/static/article/index.html
  src/main/resources/static/comment/index.html
  src/main/resources/static/index.html
  src/main/resources/static/main/index.html
  src/main/resources/static/user/index.html
Labels: Step8-3

#58 [빙빙] step9-2 추가 기능 구현
  README.md
  build.gradle
  src/main/java/db/ArticleDao.java
  src/main/java/db/JdbcUtils.java
  src/main/java/handler/Handler.java
  src/main/java/handler/StaticFileHandler.java
  src/main/java/handler/article/WriteArticleHandler.java
  src/main/java/handler/auth/CreateUserHandler.java
  src/main/java/handler/auth/LoginHandler.java
  src/main/java/handler/auth/LogoutHandler.java
  src/main/java/handler/errorHandler/InternalServerErrorHandler.java
  src/main/java/handler/errorHandler/MethodNotAllowedHandler.java
  src/main/java/handler/errorHandler/NotFoundHandler.java
  src/main/java/handler/view/TemplateHandler.java
  src/main/java/model/Article.java
  src/main/java/template/ArticleContentRenderer.java
  src/main/java/template/HeaderRenderer.java
  src/main/java/template/TemplateRenderer.java
  src/main/java/template/UserListRenderer.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/WebServer.java
  src/main/java/webserver/common/Constants.java
  src/main/java/webserver/request/MultipartParser.java
  src/main/java/webserver/request/RequestHandler.java
  src/main/java/webserver/request/RequestParser.java
  src/main/java/webserver/resolver/ContentTypeResolver.java
  src/main/java/webserver/resolver/ErrorResolver.java
  src/main/java/webserver/resolver/MethodResolver.java
  src/main/java/webserver/response/ResponseHandler.java
  src/main/java/webserver/response/ResponseHeader.java
  src/main/resources/logback.xml
  src/main/resources/static/img/default.jpeg
  src/main/resources/static/upload/images/default.jpeg
  src/main/resources/templates/article/write.html
  src/main/resources/templates/index.html
  src/test/java/handler/article/ArticleDetailHandlerTest.java
Labels: Step9-2

#59 [디노] step9-1 웹 서버 7단계 - 게시글 쓰기 구현
  README.md
  build.gradle
  deploy.sh
  enable-swap.sh
  setup.sh
  src/main/java/Exceptions/ErrorResponder.java
  src/main/java/Exceptions/UnAuthorizedException.java
  src/main/java/constants/HttpValues.java
  src/main/java/db/ArticleDao.java
  src/main/java/db/DataBaseInitializer.java
  src/main/java/db/DataBaseUtils.java
  src/main/java/db/Database.java
  src/main/java/db/UserDao.java
  src/main/java/loader/ResourceData.java
  src/main/java/loader/StaticResourceLoader.java
  src/main/java/model/Article.java
  src/main/java/model/User.java
  src/main/java/request/RequestHeader.java
  src/main/java/request/RequestReader.java
  src/main/java/response/handler/ArticleShowHandler.java
  src/main/java/response/handler/AuthenticationHandler.java
  src/main/java/response/handler/CreateArticleHandler.java
  src/main/java/response/handler/CreateUserHandler.java
  src/main/java/response/handler/Handler.java
  src/main/java/response/handler/LoginHandler.java
  src/main/java/response/handler/MainPageHandler.java
  src/main/java/response/handler/StaticResourceHandler.java
  src/main/java/response/handler/UserListHandler.java
  src/main/java/templates/ArticleModelBuilder.java
  src/main/java/templates/HeaderModelBuilder.java
  src/main/java/templates/HtmlBuilder.java
  src/main/java/templates/ModelConstants.java
  src/main/java/templates/TemplateEngine.java
  src/main/java/utils/HtmlParser.java
  src/main/java/utils/HttpRequestParser.java
  src/main/java/webserver/Dispatcher.java
  src/main/java/webserver/WebServer.java
  src/main/resources/static/article/show.html
  src/main/resources/static/article/write.html
  src/main/resources/static/error/index.html
  src/main/resources/static/index.html
  src/main/resources/static/main.css
  src/main/resources/static/user/list.html
Labels: Step9-1

#60 [케이딘] step 8-3 동적인 HTML
  src/main/java/webserver/handler/GetRequestHandler.java
  src/main/java/webserver/handler/LoginHandler.java
  src/main/java/webserver/handler/LogoutHandler.java
  src/main/java/webserver/loader/StaticResourceLoader.java
  src/main/java/webserver/loader/TemplateResourceLoader.java
  src/main/java/webserver/session/Session.java
  src/main/java/webserver/session/SessionMap.java
  src/main/java/webserver/util/Constants.java
  src/main/resources/static/index.html
  src/main/resources/templates/about.txt
  src/main/resources/templates/index.html
  src/main/resources/templates/user/list.html
Labels: Step8-3
